# Generated by Django 2.1.1 on 2018-10-06 04:13

import datetime
from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('run', '0002_auto_20181006_1212'),
    ]

    operations = [
        migrations.AddField(
            model_name='runningdata',
            name='user',
            field=models.ForeignKey(default='', on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL),
        ),
        migrations.AlterField(
            model_name='runningdata',
            name='beginTime',
            field=models.DateTimeField(default=datetime.datetime(2018, 10, 6, 12, 13, 41, 597219)),
        ),
    ]
