# Generated by Django 2.1.3 on 2018-12-22 07:11

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('run', '0003_auto_20181006_1213'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='runningdata',
            name='beginTime',
        ),
        migrations.AddField(
            model_name='runningdata',
            name='begin_time',
            field=models.DateTimeField(default=datetime.datetime(2018, 12, 22, 15, 11, 47, 329781)),
        ),
    ]
