# Generated by Django 2.1.3 on 2018-12-22 09:56

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('run', '0004_auto_20181222_1511'),
    ]

    operations = [
        migrations.AlterField(
            model_name='runningdata',
            name='begin_time',
            field=models.DateTimeField(default=datetime.datetime(2018, 12, 22, 17, 56, 48, 637954)),
        ),
    ]
